services:
  clean-architecture.api:
    image: clean-architecture.api
    build:
      context: .
      dockerfile: src/CleanArchitecture.API/Dockerfile
  clean-architecture-database:
    container_name: clean-architecture-database
    image: postgres:17.2
    ports:
      - "5432:5432"
    volumes:
      - clean-architecture-database-store:/var/lib/postgresql/data
    restart: always
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=password1@"
      - "POSTGRES_DB=clean-architecture-database"
volumes:
  clean-architecture-database-store: